In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X1=np.array([3,4,5,6])
X=np.array([2,4,5,1])
Y=np.array([17,35,46,9])


# gradient descent for linear regression

### gradient descent for 1 variable

In [3]:
c=0
for i in range(1000):
    dc=sum(-2*(Y-(c+9.2*X)))
    c=c-(dc*0.01)
print(c)


-0.8499999999999981


### gradient descent for 2 variable

In [4]:
c=0
m=0
for i in range(1000):
    dm=sum(-2*X*(Y-(c+m*X)))
    dc=sum(-2*(Y-(c+m*X)))
    c=c-(dc*0.01)
    m=m-(dm*0.01)
print("m=",m,"c=",c)


m= 9.19999993826677 c= -0.8499997675395401


### gradient descent for multiple variable

In [5]:
c=0
m=0
m1=0
for i in range(10000):
    dm1=sum(-2*X*X1*(Y-(c+m*X+m1*X1)))
    dm=sum(-2*X*(Y-(c+m*X+m1*X1)))
    dc=sum(-2*(Y-(c+m*X+m1*X1)))
    c=c-(dc*0.0001)
    m=m-(dm*0.0001)
    m1=m1-(dm1*0.0001)
print("m1=",m1,"m=",m,"c=",c)

m1= 1.0432390331513104 m= 11.282625625964563 c= -13.584384249757218


In [6]:
Y_pred=X1*m1+X*m+c
Y_pred

array([12.1105841 , 35.71907439, 48.04493905,  3.95767558])

# gradient descent for logistic regression

In [7]:
X=np.array([10,5,76,35,42,37,48,41,50,9])
Y=np.array([0,1,0,1,0,1,0,1,0,1])
c=0
m=0
for i in range(10000):
    z=1/(1 + np.exp(-(c+m*X)))
    dm=sum((z-Y)*X)
    dc=sum(z-Y)
    c=c-(dc*0.0001)
    m=m-(dm*0.0001)
print("m=",m,"c=",c)
Y_Pred=1/(1 + np.exp(-(c+m*X)))
Y_Pred

m= -0.029230173141227285 c= 0.7807202955334043


array([0.61973382, 0.65352484, 0.19142569, 0.43971082, 0.39008689,
       0.42536288, 0.34925217, 0.39706323, 0.33608537, 0.6265978 ])

In [8]:
z=np.where( Y_Pred > 0.5, 1, 0 ) 

In [9]:
correctly_classified = 0    


# counter    
count = 0    
for count in range( np.size( z ) ) :  

    if z[count] == Y[count] :            
        correctly_classified = correctly_classified + 1

    count = count + 1

print( "Accuracy on test set by our model       :  ", ( 
  correctly_classified / count ) * 100 )


Accuracy on test set by our model       :   60.0


### gradient descent for multiple variable

In [10]:
X=np.array([[10,5,76,35,42,37,48,41,50,9],[17,8,9,25,31,15,42,84,54,10]])
X=X.T
X

array([[10, 17],
       [ 5,  8],
       [76,  9],
       [35, 25],
       [42, 31],
       [37, 15],
       [48, 42],
       [41, 84],
       [50, 54],
       [ 9, 10]])

In [11]:
Y=np.array([0,1,0,1,0,1,0,1,0,1])
Y=Y.reshape(10,1)
Y

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [12]:
m,n=X.shape
b=0
w=np.zeros(n)
for i in range(10000):
    z=1/(1 + np.exp(-(X.dot(w)+b)))
    temp=(z-Y.T)
    temp=np.reshape(temp,m)
    dw=np.dot(X.T,temp)
    db=sum(temp)
    b=b-(db*0.0001)
    w=w-(dw*0.0001)
print("w=",w,"b=",b)

w= [-0.04531249  0.02257884] b= 0.6480021168300253


In [13]:
z=X.dot(w)+b
Y_Pred=1/(1 + np.exp(-z))
res=np.where( Y_Pred > 0.5, 1, 0 ) 
res

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1])

In [14]:
correctly_classified = 0       
count = 0    
for count in range( m ) :  
    if res[count] == Y[count] :            
        correctly_classified = correctly_classified + 1
    count = count + 1
print( "Accuracy on test set by our model       :  ", ( 
    correctly_classified / count ) * 100 )


Accuracy on test set by our model       :   70.0
