In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df1=pd.read_csv("pic.csv")

In [3]:
dum=pd.get_dummies(df1,columns=['det'])

In [4]:
df1=pd.melt(dum,id_vars=['variance','maximum'],
       value_vars=['det_blur'],)
df1

variance   maximum  variable  value
0    0.000131  0.155599  det_blur      1
1    0.000414  0.475520  det_blur      1
2    0.000159  0.421723  det_blur      1
3    0.000351  0.529006  det_blur      1
4    0.000114  0.166585  det_blur      1
..        ...       ...       ...    ...
695  0.004831  1.382395  det_blur      0
696  0.005011  0.987291  det_blur      0
697  0.005193  0.833827  det_blur      0
698  0.018406  1.846298  det_blur      0
699  0.003204  1.354666  det_blur      0

[700 rows x 4 columns]

In [6]:
X=df1.iloc[:,:2].values
X

array([[1.31468000e-04, 1.55599164e-01],
       [4.13639000e-04, 4.75519819e-01],
       [1.59116000e-04, 4.21723354e-01],
       ...,
       [5.19324100e-03, 8.33827193e-01],
       [1.84057080e-02, 1.84629804e+00],
       [3.20427600e-03, 1.35466584e+00]])

In [7]:
Y=df1.iloc[:,-1:].values
Y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [50]:
n2,n3=X.shape
c=0
m=np.zeros(n3)
for i in range(1000):
    z=1/(1 + np.exp(-(X*m+c)))
    temp=(z-Y.T)
    temp.reshape(tmp.n2)
    dm=np.dot(X.)
    dc=sum(z-Y)
    print(dc)
    c=c-(dc*0.0001)
    m=m-(dm*0.0001)
print("m=",m,"c=",c)

[0. 0.]
[-1.50877120e-04 -2.01899151e+00]
[-2.99113593e-04 -3.97470083e+00]
[-4.44755631e-04 -5.86858919e+00]
[-5.87848640e-04 -7.70212671e+00]
[-7.28437227e-04 -9.47678713e+00]
[-8.66565221e-04 -1.11940430e+01]
[-1.00227568e-03 -1.28553616e+01]
[-1.13561092e-03 -1.44622009e+01]
[-1.26661251e-03 -1.60160063e+01]
[-1.39532128e-03 -1.75182081e+01]
[-1.52177736e-03 -1.89702183e+01]
[-1.64602017e-03 -2.03734288e+01]
[-1.76808844e-03 -2.17292094e+01]
[-1.88802024e-03 -2.30389065e+01]
[-2.00585295e-03 -2.43038410e+01]
[-2.12162331e-03 -2.55253083e+01]
[-2.23536740e-03 -2.67045763e+01]
[-2.34712069e-03 -2.78428856e+01]
[-2.45691802e-03 -2.89414485e+01]
[-2.56479362e-03 -3.00014488e+01]
[-2.67078112e-03 -3.10240415e+01]
[-2.77491356e-03 -3.20103530e+01]
[-2.87722341e-03 -3.29614806e+01]
[-2.97774256e-03 -3.38784931e+01]
[-3.07650235e-03 -3.47624307e+01]
[-3.17353358e-03 -3.56143054e+01]
[-3.26886648e-03 -3.64351013e+01]
[-3.36253079e-03 -3.72257749e+01]
[-3.45455570e-03 -3.79872556e+01]
[-3.54

[-8.5718809e-03 -3.4521110e+01]
[-8.57267897e-03 -3.44459308e+01]
[-8.57346284e-03 -3.43710340e+01]
[-8.57423277e-03 -3.42964185e+01]
[-8.57498900e-03 -3.42220833e+01]
[-8.57573177e-03 -3.41480273e+01]
[-8.57646131e-03 -3.40742493e+01]
[-8.57717785e-03 -3.40007485e+01]
[-8.57788163e-03 -3.39275236e+01]
[-8.57857287e-03 -3.38545736e+01]
[-8.57925178e-03 -3.37818974e+01]
[-8.57991858e-03 -3.37094940e+01]
[-8.58057349e-03 -3.36373622e+01]
[-8.58121671e-03 -3.35655010e+01]
[-8.58184845e-03 -3.34939092e+01]
[-8.58246890e-03 -3.34225858e+01]
[-8.58307827e-03 -3.33515298e+01]
[-8.58367675e-03 -3.32807399e+01]
[-8.58426452e-03 -3.32102152e+01]
[-8.58484179e-03 -3.31399545e+01]
[-8.58540872e-03 -3.30699567e+01]
[-8.58596551e-03 -3.30002207e+01]
[-8.58651232e-03 -3.29307455e+01]
[-8.58704934e-03 -3.28615300e+01]
[-8.58757673e-03 -3.27925730e+01]
[-8.58809467e-03 -3.27238735e+01]
[-8.58860331e-03 -3.26554304e+01]
[-8.58910283e-03 -3.25872425e+01]
[-8.58959338e-03 -3.25193089e+01]
[-8.59007512e-03

[-8.61409220e-03 -2.05086917e+01]
[-8.61408321e-03 -2.04806654e+01]
[-8.61407416e-03 -2.04527151e+01]
[-8.61406503e-03 -2.04248406e+01]
[-8.61405584e-03 -2.03970416e+01]
[-8.61404658e-03 -2.03693177e+01]
[-8.61403726e-03 -2.03416686e+01]
[-8.61402787e-03 -2.03140942e+01]
[-8.61401842e-03 -2.02865940e+01]
[-8.61400891e-03 -2.02591678e+01]
[-8.61399933e-03 -2.02318153e+01]
[-8.61398970e-03 -2.02045363e+01]
[-8.61398001e-03 -2.01773303e+01]
[-8.61397026e-03 -2.01501973e+01]
[-8.61396046e-03 -2.01231368e+01]
[-8.61395060e-03 -2.00961486e+01]
[-8.61394068e-03 -2.00692324e+01]
[-8.61393071e-03 -2.00423879e+01]
[-8.61392069e-03 -2.00156149e+01]
[-8.61391062e-03 -1.99889131e+01]
[-8.61390049e-03 -1.99622822e+01]
[-8.61389032e-03 -1.99357219e+01]
[-8.61388009e-03 -1.99092320e+01]
[-8.61386982e-03 -1.98828121e+01]
[-8.61385950e-03 -1.98564621e+01]
[-8.61384914e-03 -1.98301817e+01]
[-8.61383873e-03 -1.98039705e+01]
[-8.61382827e-03 -1.97778284e+01]
[-8.61381777e-03 -1.97517551e+01]
[-8.61380723e-

[-8.61099414e-03 -1.51921571e+01]
[-8.61098119e-03 -1.51768376e+01]
[-8.61096825e-03 -1.51615496e+01]
[-8.61095530e-03 -1.51462929e+01]
[-8.61094235e-03 -1.51310675e+01]
[-8.61092941e-03 -1.51158731e+01]
[-8.61091646e-03 -1.51007098e+01]
[-8.61090351e-03 -1.50855774e+01]
[-8.61089056e-03 -1.50704759e+01]
[-8.61087760e-03 -1.50554052e+01]
[-8.61086465e-03 -1.50403651e+01]
[-8.61085170e-03 -1.50253556e+01]
[-8.61083875e-03 -1.50103765e+01]
[-8.61082579e-03 -1.49954279e+01]
[-8.61081284e-03 -1.49805095e+01]
[-8.61079988e-03 -1.49656214e+01]
[-8.61078693e-03 -1.49507633e+01]
[-8.61077397e-03 -1.49359353e+01]
[-8.61076101e-03 -1.49211372e+01]
[-8.61074805e-03 -1.49063690e+01]
[-8.61073510e-03 -1.48916305e+01]
[-8.61072214e-03 -1.48769217e+01]
[-8.61070918e-03 -1.48622425e+01]
[-8.61069622e-03 -1.48475927e+01]
[-8.61068325e-03 -1.48329724e+01]
[-8.61067029e-03 -1.48183814e+01]
[-8.61065733e-03 -1.48038196e+01]
[-8.61064437e-03 -1.47892869e+01]
[-8.61063141e-03 -1.47747833e+01]
[-8.61061844e-

In [42]:
z=X*m+c

In [43]:
Y_Pred=1/(1 + np.exp(-z))
Y_Pred

array([[0.50019759, 0.88398046],
       [0.50018584, 0.64681841],
       [0.50019644, 0.69947619],
       ...,
       [0.49998668, 0.27060323],
       [0.49943614, 0.00405711],
       [0.50006956, 0.03514605]])

In [26]:
m=np.array([0,0])
c=0
z=1/(1 + np.exp(-(c+(X.dot(0)))))
z-Y

array([[-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5],
       ...,
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])

In [21]:
X

array([[1.31468000e-04, 1.55599164e-01],
       [4.13639000e-04, 4.75519819e-01],
       [1.59116000e-04, 4.21723354e-01],
       ...,
       [5.19324100e-03, 8.33827193e-01],
       [1.84057080e-02, 1.84629804e+00],
       [3.20427600e-03, 1.35466584e+00]])

In [ ]:
z=1/(1 + np.exp(-(X*m+c)))
dm=sum((z-Y)*X)
dc=sum(z-Y)
print(dc)
c=c-(dc*0.0001)
m=m-(dm*0.0001)

In [35]:
m=0
c=0
z=1/(1 + np.exp(-(X.dot(m)+c)))
z-Y

array([[-0.5, -0.5],
       [-0.5, -0.5],
       [-0.5, -0.5],
       ...,
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])

In [37]:
z

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       ...,
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [38]:
Y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [39]:
Y.T

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 