In [1]:
import numpy as np
l=[[1,2,3],[4,5,6]]
ary=np.array(l)
l

[[1, 2, 3], [4, 5, 6]]

In [2]:
ary.dtype

dtype('int32')

In [3]:
fl_ar=ary.astype(np.float64)
fl_ar

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
ary.itemsize

4

In [5]:
ary.size

6

In [6]:
ary.ndim

2

In [7]:
ary.shape

(2, 3)

In [8]:
generator_expression = (i for i in range(10) if i % 2)
np.fromiter(generator_expression, dtype=int)


array([1, 3, 5, 7, 9])

In [9]:
np.empty([3,3],dtype=int)

array([[         0,          1,          0],
       [     32765,        476,          0],
       [       768,      32766, -790101360]])

In [10]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
np.eye(4,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.diag([4,4,4])

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [13]:
np.arange(4.5,10.5)

array([4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
range(5)

range(0, 5)

In [16]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [17]:
ar2=np.array([1,2,3,4,5])
ar2[0]

1

In [18]:
ar2[:2]

array([1, 2])

In [19]:
ar3=ary

In [20]:
ar3[0,0]

1

In [21]:
ar3[-1,-1]

6

In [22]:
ar3[0,2]

3

In [23]:
ar3[0]

array([1, 2, 3])

In [24]:
ar3=np.append(ar3,np.array([[7,8,9]]),axis=0)

In [25]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
ar3[0]

array([1, 2, 3])

In [27]:
ar3[1]

array([4, 5, 6])

In [28]:
ar3[2]

array([7, 8, 9])

In [29]:
ar3[0,1]

2

In [30]:
ar3[1,2]

6

In [32]:
ar3[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [33]:
ar3[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar3[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
ar3[:1]

array([[1, 2, 3]])

In [36]:
ar3[:,1]

array([2, 5, 8])

In [37]:
ar3[:,0]

array([1, 4, 7])

In [38]:
ar3[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ar3[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
ar3[1:,1:]

array([[5, 6],
       [8, 9]])

In [41]:
ar3[1:,1:2]

array([[5],
       [8]])

In [42]:
lst=[[1,2,3],[4,5,6]]
for rid,rvl in enumerate(l):
    for cid,cvl in enumerate(rvl):
        print(rid,rvl,cid,cvl,sep=",")

0,[1, 2, 3],0,1
0,[1, 2, 3],1,2
0,[1, 2, 3],2,3
1,[4, 5, 6],0,4
1,[4, 5, 6],1,5
1,[4, 5, 6],2,6


In [43]:
a,b=enumerate(lst)
print(b)

(1, [4, 5, 6])


In [44]:
[[cell + 1 for cell in row] for row in lst]

[[2, 3, 4], [5, 6, 7]]

In [45]:
np.add(lst,1)

array([[2, 3, 4],
       [5, 6, 7]])

In [46]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.subtract.reduce(ar3)

array([-10, -11, -12])

In [48]:
ar3=np.append(ar3,np.array([[2,6,11]]),axis=0)
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  6, 11]])

In [49]:
ar3=np.delete(ar3, (4), axis=0)
ar3

IndexError: index 4 is out of bounds for axis 0 with size 4

In [50]:
np.subtract.reduce(ar3,axis=1)

array([ -4,  -7, -10, -15])

In [51]:
np.multiply.reduce(ar3,axis=0)

array([  56,  480, 1782])

In [52]:
np.sum(ar3)

64

In [53]:
ar3.sum()

64

In [54]:
np.sort(ar3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  6, 11]])

In [55]:
ar3=np.append(ar3,np.array([[9,11,1]]),axis=0)

In [56]:
np.sort(ar3,axis=1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  6, 11],
       [ 1,  9, 11]])

In [57]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  6, 11],
       [ 9, 11,  1]])

In [64]:
np.array([[1],[2],[3],[4],[5]])+ar3

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [ 6, 10, 15],
       [14, 16,  6]])

In [65]:
ary=np.array([[1,2,3],[4,5,6]])

In [66]:
fr=ary[0]

In [67]:
fr+=99
ary

array([[100, 101, 102],
       [  4,   5,   6]])

In [70]:
center_col = ary[:, 1]
center_col += 99

In [71]:
ary

array([[100, 200, 102],
       [  4, 104,   6]])

In [75]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])
first_row = ary[:1].copy()
first_row += 99
ary


array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.may_share_memory(first_row, ary)

False

In [77]:
ary[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [79]:
ary>3

array([[False, False, False],
       [ True,  True,  True]])

In [80]:
ar3[ar3>3]

array([ 4,  5,  6,  7,  8,  9,  6, 11,  9, 11])

In [87]:
ar3[(ar3>3) & (ar3<10)]

array([4, 5, 6, 7, 8, 9, 6, 9])

In [89]:
mask=(ar3>3) & (ar3<10)
mask

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [ True, False, False]])

In [91]:
ar3[mask]

array([4, 5, 6, 7, 8, 9, 6, 9])

In [92]:
mask.sum()

8

In [93]:
mask.nonzero()

(array([1, 1, 1, 2, 2, 2, 3, 4], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 1, 0], dtype=int64))

In [94]:
np.where(ar3>2)

(array([0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2, 1, 2, 0, 1], dtype=int64))

In [96]:
ar3[mask]=1
ar3

array([[ 1,  2,  3],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 2,  1, 11],
       [ 1, 11,  1]])

In [216]:
np.random.seed(2)
np.random.rand(3)

array([0.4359949 , 0.02592623, 0.54966248])

In [219]:
rng1 = np.random.RandomState(seed=123)
rng1.rand(3)


array([0.69646919, 0.28613933, 0.22685145])

In [229]:
rng1 = np.random.RandomState(seed=123)
rng1.randn(2)


array([-1.0856306 ,  0.99734545])

In [230]:
rng2 = np.random.RandomState(seed=123)
z_scores = rng2.randn(100, 2)

In [231]:
import matplotlib.pyplot as plt
plt.scatter(z_scores[:, 0], z_scores[:, 1])
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [239]:
ar1d = np.array([1, 2, 3, 4, 5, 6])
ar2d= ar1d.reshape(6, 1)
ar2d+=2
ar1d

array([3, 4, 5, 6, 7, 8])

In [240]:
ar2d

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [245]:
ar1d.reshape(1, -1)

array([[3, 4, 5, 6, 7, 8]])

In [246]:
ar2d.ravel()

array([3, 4, 5, 6, 7, 8])

In [247]:
ar2d

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [248]:
np.may_share_memory(ar2d.flatten(), ar2d)

False

In [249]:
np.may_share_memory(ar2d.ravel(), ar2d)

True

In [250]:
ary = np.array([[1, 2, 3]])
np.concatenate((ary, ary), axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [251]:
ary = np.array([[1, 2, 3]])
np.concatenate((ary, ary), axis=1)

array([[1, 2, 3, 1, 2, 3]])

In [255]:
ary

array([[1, 2, 3]])

In [256]:
ar3

array([[ 1,  2,  3],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 2,  1, 11],
       [ 1, 11,  1]])

In [257]:
ary*ar3

array([[ 1,  4,  9],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 2,  2, 33],
       [ 1, 22,  3]])

In [258]:
rv=np.array([8,9,5])
rv

array([8, 9, 5])

In [259]:
cv=rv[:,np.newaxis]

In [260]:
cv

array([[8],
       [9],
       [5]])

In [261]:
mat= np.array([[1, 2, 3],[4, 5, 6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [264]:
np.matmul(mat,cv)

array([[ 41],
       [107]])

In [265]:
np.matmul(mat,rv)

array([ 41, 107])

In [266]:
np.matmul(rv,rv)

170

In [267]:
np.dot(rv,rv)

170

In [268]:
np.dot(mat,cv)

array([[ 41],
       [107]])

In [269]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [270]:
mat.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [271]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [272]:
ary = np.array([1, 1, 2, 3, 1, 5])
ary_set = np.unique(ary)
ary_set

array([1, 2, 3, 5])

In [279]:
ary1 = np.array([1, 2, 4, 4, 3])
ary2 = np.array([3, 4, 4, 5, 6])
np.intersect1d(ary1, ary2, assume_unique=False)

array([3, 4])

In [281]:
np.setdiff1d(ary2, ary1, assume_unique=True)


array([5, 6])

In [284]:
np.union1d(ary1, ary2,)

array([1, 2, 3, 4, 5, 6])

In [287]:
myar1=np.array([[ 1,  4,  9],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 2,  2, 33],
       [ 1, 22,  3]])
myar1

array([[ 1,  4,  9],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 2,  2, 33],
       [ 1, 22,  3]])

In [288]:
myar2=np.array([[ 1,  4,  9],
       [ 9,  62, 33],
       [ 0, 22,  3]])
myar2

array([[ 1,  4,  9],
       [ 9, 62, 33],
       [ 0, 22,  3]])

In [289]:
np.save("ar-data.npy",myar1)


In [290]:
np.load("ar-data.npy")

array([[ 1,  4,  9],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 2,  2, 33],
       [ 1, 22,  3]])

In [308]:
np.savez('ar-data3.npz',myar1,myar2)

In [315]:
k=np.load('ar-data3.npz')
k['arr_0']

array([[ 1,  4,  9],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 2,  2, 33],
       [ 1, 22,  3]])

In [314]:
np.savez('ary-data.npz', ary1, ary2)
d = np.load('ary-data.npz')
d.keys()
d['arr_1']


array([3, 4, 4, 5, 6])

In [316]:
nm={'ar1':myar1,'ar2':myar2}
np.savez("nwdt.npz",**nm)

In [323]:
l=np.load("nwdt.npz")
k[for i in l.keys()]

k

SyntaxError: invalid syntax (<ipython-input-323-c4cbd9955896>, line 2)